import type { jsPDF } from "jspdf";
import type { ShopProfile } from "./shopProfile";

// ============================================================
// IMPORTANT LIMITATION, read before touching this file:
//
// jsPDF's built-in fonts (Helvetica/Times/Courier) only cover Latin
// script — they cannot render Pashto or Dari (Arabic-script) glyphs.
// True native-script PDFs would need an embedded Unicode font (e.g.
// Noto Sans Arabic converted to jsPDF's font format), which is a
// meaningfully bigger undertaking (font licensing + a multi-hundred-KB
// asset + bidi text layout) than this phase's scope.
//
// The tradeoff made here: the on-screen "View" receipt (ReceiptModal)
// IS fully localized — it's plain HTML/CSS and renders any script
// fine. The DOWNLOADED PDF always renders its labels in English and
// its numbers in Western digits, regardless of the app's language
// setting, so it stays legible instead of showing blank boxes where
// Pashto/Dari text would be. This is called out again in the UI
// itself (see the small note under the Download button in
// ReceiptModal) rather than only living here as a code comment.
// ============================================================

const PAGE_WIDTH = 210; // A4 mm
const MARGIN = 18;
let cursorY = 0;

function line(doc: jsPDF, y: number) {
  doc.setDrawColor(220, 226, 240);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
}

function money(n: number): string {
  return n.toLocaleString("en-US", { maximumFractionDigits: 2 });
}

function writeShopHeader(doc: jsPDF, shop: ShopProfile): number {
  cursorY = 20;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(16, 27, 51);
  doc.text(shop.shop_name, MARGIN, cursorY);

  cursorY += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(90, 100, 120);
  doc.text(shop.owner_name, MARGIN, cursorY);

  cursorY += 5;
  const contactLine = [
    `Mobile: ${shop.phone_number}`,
    shop.whatsapp_number ? `WhatsApp: ${shop.whatsapp_number}` : null,
  ]
    .filter(Boolean)
    .join("   |   ");
  doc.text(contactLine, MARGIN, cursorY);

  if (shop.address) {
    cursorY += 5;
    doc.text(shop.address, MARGIN, cursorY);
  }

  cursorY += 6;
  line(doc, cursorY);
  cursorY += 10;
  return cursorY;
}

function writeFooter(doc: jsPDF) {
  doc.setFontSize(8);
  doc.setTextColor(160, 168, 190);
  doc.text(
    `Generated by Saudagar on ${new Date().toLocaleString("en-US")}`,
    MARGIN,
    287
  );
}

interface TransactionReceiptInput {
  shop: ShopProfile;
  currency: string;
  transactionType: "purchase" | "sale";
  commodityName: string;
  unit: string;
  quantity: number;
  unitCost: number | null;
  transportCost: number;
  porterFee: number;
  createdAt: string;
  partyName: string | null;
  partyPhone: string | null;
  partyWhatsapp: string | null;
  partyAddress: string | null;
}

export async function buildTransactionReceiptPdf(input: TransactionReceiptInput): Promise<jsPDF> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  writeShopHeader(doc, input.shop);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(30, 99, 214);
  doc.text(input.transactionType === "purchase" ? "PURCHASE RECEIPT" : "SALE RECEIPT", MARGIN, cursorY);
  cursorY += 6;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(90, 100, 120);
  doc.text(`Date: ${new Date(input.createdAt).toLocaleString("en-US")}`, MARGIN, cursorY);
  cursorY += 10;

  if (input.partyName) {
    doc.setFont("helvetica", "bold");
    doc.setTextColor(16, 27, 51);
    doc.text(input.transactionType === "purchase" ? "Purchased from:" : "Sold to:", MARGIN, cursorY);
    cursorY += 5.5;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(90, 100, 120);
    doc.text(input.partyName, MARGIN, cursorY);
    cursorY += 5;
    const partyContact = [
      input.partyPhone ? `Mobile: ${input.partyPhone}` : null,
      input.partyWhatsapp ? `WhatsApp: ${input.partyWhatsapp}` : null,
    ]
      .filter(Boolean)
      .join("   |   ");
    if (partyContact) {
      doc.text(partyContact, MARGIN, cursorY);
      cursorY += 5;
    }
    if (input.partyAddress) {
      doc.text(input.partyAddress, MARGIN, cursorY);
      cursorY += 5;
    }
    cursorY += 4;
  }

  line(doc, cursorY);
  cursorY += 8;

  // Line-item table (drawn manually — no autotable plugin, keeps the
  // bundle smaller for a receipt this simple).
  const cols = [MARGIN, 95, 125, 155];
  doc.setFont("helvetica", "bold");
  doc.setTextColor(16, 27, 51);
  doc.text("Item", cols[0], cursorY);
  doc.text("Quantity", cols[1], cursorY);
  doc.text("Unit Cost", cols[2], cursorY);
  doc.text("Total", cols[3], cursorY);
  cursorY += 4;
  line(doc, cursorY);
  cursorY += 6;

  doc.setFont("helvetica", "normal");
  doc.setTextColor(60, 68, 90);
  const lineTotal = input.unitCost !== null ? input.quantity * input.unitCost : 0;
  doc.text(input.commodityName, cols[0], cursorY);
  doc.text(`${money(input.quantity)} ${input.unit}`, cols[1], cursorY);
  doc.text(input.unitCost !== null ? money(input.unitCost) : "-", cols[2], cursorY);
  doc.text(input.unitCost !== null ? money(lineTotal) : "-", cols[3], cursorY);
  cursorY += 8;

  if (input.transportCost > 0) {
    doc.text("Transport cost", cols[0], cursorY);
    doc.text(money(input.transportCost), cols[3], cursorY);
    cursorY += 6;
  }
  if (input.porterFee > 0) {
    doc.text("Porter/worker fee", cols[0], cursorY);
    doc.text(money(input.porterFee), cols[3], cursorY);
    cursorY += 6;
  }

  cursorY += 2;
  line(doc, cursorY);
  cursorY += 8;

  const grandTotal = lineTotal + input.transportCost + input.porterFee;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(16, 27, 51);
  doc.text("Total", cols[0], cursorY);
  doc.text(`${input.currency} ${money(grandTotal)}`, cols[3], cursorY);

  writeFooter(doc);
  return doc;
}

interface LedgerEntryLine {
  entry_date: string;
  entry_type: "credit" | "debit";
  amount: number;
  currency: "AFN" | "PKR";
  note: string | null;
}

interface LedgerReceiptInput {
  shop: ShopProfile;
  counterpartyName: string;
  counterpartyPhone: string;
  counterpartyWhatsapp: string | null;
  counterpartyAddress: string | null;
  entries: LedgerEntryLine[];
}

export async function buildLedgerReceiptPdf(input: LedgerReceiptInput): Promise<jsPDF> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  writeShopHeader(doc, input.shop);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(30, 99, 214);
  doc.text("ACCOUNT STATEMENT", MARGIN, cursorY);
  cursorY += 8;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(16, 27, 51);
  doc.text(`Account: ${input.counterpartyName}`, MARGIN, cursorY);
  cursorY += 5.5;
  doc.setFont("helvetica", "normal");
  doc.setTextColor(90, 100, 120);
  const cpContact = [
    `Mobile: ${input.counterpartyPhone}`,
    input.counterpartyWhatsapp ? `WhatsApp: ${input.counterpartyWhatsapp}` : null,
  ]
    .filter(Boolean)
    .join("   |   ");
  doc.text(cpContact, MARGIN, cursorY);
  cursorY += 5;
  if (input.counterpartyAddress) {
    doc.text(input.counterpartyAddress, MARGIN, cursorY);
    cursorY += 5;
  }
  cursorY += 4;
  line(doc, cursorY);
  cursorY += 10;

  const cols = [MARGIN, 90, 130, 165];

  // A contact can hold both AFN and PKR entries at once (never summed
  // together) — render one table + one totals block per currency
  // that's actually present, so a mixed account produces a receipt
  // with clearly separated AFN and PKR sections rather than a single
  // misleading combined figure.
  const currencies = (["AFN", "PKR"] as const).filter((c) => input.entries.some((e) => e.currency === c));

  for (const currency of currencies) {
    if (cursorY > 250) {
      writeFooter(doc);
      doc.addPage();
      cursorY = 20;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(30, 99, 214);
    doc.text(currency, MARGIN, cursorY);
    cursorY += 6;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9.5);
    doc.setTextColor(16, 27, 51);
    doc.text("Date", cols[0], cursorY);
    doc.text("Note", cols[1], cursorY);
    doc.text("Type", cols[2], cursorY);
    doc.text("Amount", cols[3], cursorY);
    cursorY += 4;
    line(doc, cursorY);
    cursorY += 6;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);

    let given = 0;
    let received = 0;
    // Oldest-first for a statement (reads like a running history),
    // even though the on-screen ledger elsewhere shows newest-first.
    const chronological = input.entries
      .filter((e) => e.currency === currency)
      .sort((a, b) => a.entry_date.localeCompare(b.entry_date));

    for (const entry of chronological) {
      if (cursorY > 270) {
        writeFooter(doc);
        doc.addPage();
        cursorY = 20;
      }
      if (entry.entry_type === "credit") given += entry.amount;
      else received += entry.amount;

      doc.setTextColor(60, 68, 90);
      doc.text(new Date(entry.entry_date).toLocaleDateString("en-US"), cols[0], cursorY);
      doc.text((entry.note ?? "-").slice(0, 28), cols[1], cursorY);
      doc.text(entry.entry_type === "credit" ? "Given" : "Received", cols[2], cursorY);
      doc.setTextColor(
        entry.entry_type === "credit" ? 29 : 226,
        entry.entry_type === "credit" ? 164 : 61,
        entry.entry_type === "credit" ? 99 : 61
      );
      doc.text(`${entry.entry_type === "credit" ? "+" : "-"}${money(entry.amount)}`, cols[3], cursorY);
      cursorY += 6;
    }

    cursorY += 2;
    line(doc, cursorY);
    cursorY += 8;

    const balance = given - received;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(90, 100, 120);
    doc.text(`Total Given: ${money(given)}`, cols[0], cursorY);
    doc.text(`Total Received: ${money(received)}`, cols[2], cursorY);
    cursorY += 8;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(16, 27, 51);
    doc.text("Balance", cols[0], cursorY);
    doc.text(`${currency} ${balance < 0 ? "-" : ""}${money(Math.abs(balance))}`, cols[3], cursorY);
    cursorY += 14;
  }

  writeFooter(doc);
  return doc;
}

export function downloadPdf(doc: jsPDF, filename: string) {
  doc.save(filename);
}

// wa.me can only pre-fill TEXT, not attach a file — there's no
// click-to-chat API for sending an actual PDF, so the WhatsApp button
// shares a text summary rather than the generated receipt file
// itself. If a phone number is known (the transaction's counterparty,
// or the ledger contact), the chat opens directly with them;
// otherwise it opens WhatsApp with the message ready to forward to
// whoever the user picks.
export function whatsAppShareLink(text: string, phone?: string | null): string {
  const encoded = encodeURIComponent(text);
  const digits = phone ? phone.replace(/\D/g, "") : "";
  return digits ? `https://wa.me/${digits}?text=${encoded}` : `https://wa.me/?text=${encoded}`;
}
